name: mtxo_labs_edtech
description: MTXO Labs EdTech Platform - Advanced learning environment for cutting-edge technology and AI education.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' 

# The app version and build number
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  
  # State Management
  provider: ^6.0.5
  flutter_bloc: ^8.1.3
  
  # Navigation
  go_router: ^10.1.2
  
  # UI Components
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  flutter_animate: ^4.2.0
  shimmer: ^3.0.0
  flutter_markdown: ^0.6.17
  flutter_spinkit: ^5.2.0
  lottie: ^2.6.0
  
  # Network and API
  dio: ^5.3.2
  http: ^1.1.0
  json_annotation: ^4.8.1
  connectivity_plus: ^4.0.2
  
  # Auth and Security
  flutter_secure_storage: ^8.0.0
  jwt_decoder: ^2.0.1
  
  # Storage
  shared_preferences: ^2.2.1
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  
  # Payments
  flutter_stripe: ^9.3.0
  
  # Utils
  intl: ^0.18.1
  url_launcher: ^6.1.14
  device_info_plus: ^9.0.3
  package_info_plus: ^4.1.0
  logger: ^1.4.0
  
  # Video Players
  video_player: ^2.7.1
  chewie: ^1.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  flutter_native_splash: ^2.3.2
  flutter_launcher_icons: ^0.13.1

# Flutter configuration
flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    
  # Fonts
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700